<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

aaaDurctest.vote by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in vote.php 

DURC Generated At: Monday 1st of January 2018 04:58:04 PM
*/

class DURC_vote extends DURCModel{

        // the datbase for this model
        protected $table = 'aaaDurctest.vote';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'post', //from belongs to
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'post_id' => 'int',
		'votenum' => 'varchar',
		'updated_at' => 'datetime',
		'created_at' => 'datetime',
			]; //end field_type_map

		//everything is fillable by default
		protected $guarded = [];


		//DURC HAS_MANY SECTION
			//DURC did not detect any has_many relationships

		//DURC BELONGS_TO SECTION
/**
*	get the single post for this DURC_vote
*/
	public function post(){
		return $this->belongsTo('App\post','post_id','id');
	}



}//end of DURC_vote