<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

northwind_data.order by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in order.php 

DURC Generated At: Monday 1st of January 2018 04:58:04 PM
*/

class DURC_order extends DURCModel{

        // the datbase for this model
        protected $table = 'northwind_data.order';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'invoice', //from from many
			'orderdetail', //from from many
			'employee', //from belongs to
			'customer', //from belongs to
			'shipper', //from belongs to
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'employee_id' => 'int',
		'customer_id' => 'int',
		'orderDate' => 'datetime',
		'shippedDate' => 'datetime',
		'shipper_id' => 'int',
		'shipName' => 'varchar',
		'shipAddress' => 'longtext',
		'shipCity' => 'varchar',
		'shipStateProvince' => 'varchar',
		'shipZipPostalCode' => 'varchar',
		'shipCountryRegion' => 'varchar',
		'shippingFee' => 'decimal',
		'taxes' => 'decimal',
		'paymentType' => 'varchar',
		'paidDate' => 'datetime',
		'notes' => 'longtext',
		'taxRate' => 'double',
		'taxStatus_id' => 'tinyint',
		'status_id' => 'tinyint',
			]; //end field_type_map

		//everything is fillable by default
		protected $guarded = [];


		//DURC HAS_MANY SECTION
/**
*	get all the invoice for this DURC_order
*/
	public function invoice(){
		return $this->hasMany('App\invoice','order_id','id');
	}


/**
*	get all the orderdetail for this DURC_order
*/
	public function orderdetail(){
		return $this->hasMany('App\orderdetail','order_id','id');
	}



		//DURC BELONGS_TO SECTION
/**
*	get the single employee for this DURC_order
*/
	public function employee(){
		return $this->belongsTo('App\employee','employee_id','id');
	}


/**
*	get the single customer for this DURC_order
*/
	public function customer(){
		return $this->belongsTo('App\customer','customer_id','id');
	}


/**
*	get the single shipper for this DURC_order
*/
	public function shipper(){
		return $this->belongsTo('App\shipper','shipper_id','id');
	}



}//end of DURC_order