<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

northwind_data.orderDetail by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in orderdetail.php 

*/

class orderdetail extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'northwind_data.orderDetail';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'order', //from belongs to
			'product', //from belongs to
			'purchaseorder', //from belongs to
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'order_id' => 'int',
		'product_id' => 'int',
		'quantity' => 'decimal',
		'unitPrice' => 'decimal',
		'discount' => 'double',
		'status_id' => 'int',
		'dateAllocated' => 'datetime',
		'PurchaseOrder_id' => 'int',
		'inventory_id' => 'int',
			]; //end field_type_map

		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

/**
*	get the single order for this orderdetail
*/
	public function order(){
		return $this->belongsTo('App\order','order_id','id');
	}


/**
*	get the single product for this orderdetail
*/
	public function product(){
		return $this->belongsTo('App\product','product_id','id');
	}


/**
*	get the single purchaseorder for this orderdetail
*/
	public function purchaseorder(){
		return $this->belongsTo('App\purchaseorder','PurchaseOrder_id','id');
	}



}//end of orderdetail