<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

northwind_data.tags_report by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in tags_report.php 

*/

class tags_report extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'northwind_data.tags_report';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'bigint',
		'field_to_bold_in_report_display' => 'varchar',
		'field_to_hide_by_default' => 'varchar',
		'field_to_italic_in_report_display' => 'varchar',
		'field_to_right_align_in_report' => 'varchar',
		'field_to_bolditalic_in_report_display' => 'varchar',
		'numeric_field' => 'int',
		'decimal_field' => 'decimal',
		'currency_field' => 'varchar',
		'percent_field' => 'int',
		'url_field' => 'varchar',
		'time_field' => 'time',
		'date_field' => 'date',
		'datetime_field' => 'datetime',
			]; //end field_type_map
		
		// Indicate which fields are nullable
		static $non_nullable_fields = [
			]; // End of nullable fields

		// Indicate which fields are nullable
		static $default_values = [
			]; // End of default values
        
		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `northwind_data`.`tags_report` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `field_to_bold_in_report_display` varchar(255) NOT NULL,
  `field_to_hide_by_default` varchar(255) NOT NULL,
  `field_to_italic_in_report_display` varchar(255) NOT NULL,
  `field_to_right_align_in_report` varchar(255) NOT NULL,
  `field_to_bolditalic_in_report_display` varchar(255) NOT NULL,
  `numeric_field` int(11) NOT NULL,
  `decimal_field` decimal(10,4) NOT NULL,
  `currency_field` varchar(255) NOT NULL,
  `percent_field` int(11) NOT NULL,
  `url_field` varchar(255) NOT NULL,
  `time_field` time NOT NULL,
  `date_field` date NOT NULL,
  `datetime_field` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4
*/


}//end of tags_report