<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

aaaDurctest.vote by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in vote.php 

*/

class vote extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'aaaDurctest.vote';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'post', //from belongs to
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'post_id' => 'int',
		'votenum' => 'varchar',
		'updated_at' => 'datetime',
		'created_at' => 'datetime',
			]; //end field_type_map
		
		// Indicate which fields are nullable
		static $non_nullable_fields = [
			]; // End of nullable fields

		// Indicate which fields are nullable
		static $default_values = [
			]; // End of default values
        
		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

/**
*	get the single post for this vote
*/
	public function post(){
		return $this->belongsTo('App\post','post_id','id');
	}



//Originating SQL Schema
/*
CREATE TABLE `aaaDurctest`.`vote` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `post_id` int(11) NOT NULL,
  `votenum` varchar(11) NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1
*/


}//end of vote