<?php
/*
	This test route is automatically added.
	IF you would like to quickly see and test all of the index routes that are generated by DURC
	to use: http://[baseUrl]/durctest
	
	To remove routes from production, remove the require for this file from the register() method
	of the DURCServiceProvider.

*/

//This closure lists all of the index routes that DURC knows about...
Route::get('durctest', function () {
    $route_list = [ 




 			'/DURC/author', //from: aaaDurctest.author 
 			'/DURC/author/create', //from: aaaDurctest.author 
 			'/DURC/author/1', //from: aaaDurctest.author 
 			'/DURC/author/1/edit', //from: aaaDurctest.author 
 			'/DURC/author_book', //from: aaaDurctest.author_book 
 			'/DURC/author_book/create', //from: aaaDurctest.author_book 
 			'/DURC/author_book/1', //from: aaaDurctest.author_book 
 			'/DURC/author_book/1/edit', //from: aaaDurctest.author_book 
 			'/DURC/authortype', //from: aaaDurctest.authortype 
 			'/DURC/authortype/create', //from: aaaDurctest.authortype 
 			'/DURC/authortype/1', //from: aaaDurctest.authortype 
 			'/DURC/authortype/1/edit', //from: aaaDurctest.authortype 
 			'/DURC/book', //from: aaaDurctest.book 
 			'/DURC/book/create', //from: aaaDurctest.book 
 			'/DURC/book/1', //from: aaaDurctest.book 
 			'/DURC/book/1/edit', //from: aaaDurctest.book 
 			'/DURC/booleantest', //from: aaaDurctest.booleantest 
 			'/DURC/booleantest/create', //from: aaaDurctest.booleantest 
 			'/DURC/booleantest/1', //from: aaaDurctest.booleantest 
 			'/DURC/booleantest/1/edit', //from: aaaDurctest.booleantest 
 			'/DURC/comment', //from: aaaDurctest.comment 
 			'/DURC/comment/create', //from: aaaDurctest.comment 
 			'/DURC/comment/1', //from: aaaDurctest.comment 
 			'/DURC/comment/1/edit', //from: aaaDurctest.comment 
 			'/DURC/donation', //from: aaaDurctest.donation 
 			'/DURC/donation/create', //from: aaaDurctest.donation 
 			'/DURC/donation/1', //from: aaaDurctest.donation 
 			'/DURC/donation/1/edit', //from: aaaDurctest.donation 
 			'/DURC/foreignkeytestgizmo', //from: aaaDurctest.foreignkeytestgizmo 
 			'/DURC/foreignkeytestgizmo/create', //from: aaaDurctest.foreignkeytestgizmo 
 			'/DURC/foreignkeytestgizmo/1', //from: aaaDurctest.foreignkeytestgizmo 
 			'/DURC/foreignkeytestgizmo/1/edit', //from: aaaDurctest.foreignkeytestgizmo 
 			'/DURC/foreignkeytestthingy', //from: aaaDurctest.foreignkeytestthingy 
 			'/DURC/foreignkeytestthingy/create', //from: aaaDurctest.foreignkeytestthingy 
 			'/DURC/foreignkeytestthingy/1', //from: aaaDurctest.foreignkeytestthingy 
 			'/DURC/foreignkeytestthingy/1/edit', //from: aaaDurctest.foreignkeytestthingy 
 			'/DURC/funnything', //from: aaaDurctest.funnything 
 			'/DURC/funnything/create', //from: aaaDurctest.funnything 
 			'/DURC/funnything/1', //from: aaaDurctest.funnything 
 			'/DURC/funnything/1/edit', //from: aaaDurctest.funnything 
 			'/DURC/post', //from: aaaDurctest.post 
 			'/DURC/post/create', //from: aaaDurctest.post 
 			'/DURC/post/1', //from: aaaDurctest.post 
 			'/DURC/post/1/edit', //from: aaaDurctest.post 
 			'/DURC/sibling', //from: aaaDurctest.sibling 
 			'/DURC/sibling/create', //from: aaaDurctest.sibling 
 			'/DURC/sibling/1', //from: aaaDurctest.sibling 
 			'/DURC/sibling/1/edit', //from: aaaDurctest.sibling 
 			'/DURC/test_boolean', //from: aaaDurctest.test_boolean 
 			'/DURC/test_boolean/create', //from: aaaDurctest.test_boolean 
 			'/DURC/test_boolean/1', //from: aaaDurctest.test_boolean 
 			'/DURC/test_boolean/1/edit', //from: aaaDurctest.test_boolean 
 			'/DURC/test_created_only', //from: aaaDurctest.test_created_only 
 			'/DURC/test_created_only/create', //from: aaaDurctest.test_created_only 
 			'/DURC/test_created_only/1', //from: aaaDurctest.test_created_only 
 			'/DURC/test_created_only/1/edit', //from: aaaDurctest.test_created_only 
 			'/DURC/vote', //from: aaaDurctest.vote 
 			'/DURC/vote/create', //from: aaaDurctest.vote 
 			'/DURC/vote/1', //from: aaaDurctest.vote 
 			'/DURC/vote/1/edit', //from: aaaDurctest.vote 
 			'/DURC/nonprofitcorp', //from: irs.nonprofitcorp 
 			'/DURC/nonprofitcorp/create', //from: irs.nonprofitcorp 
 			'/DURC/nonprofitcorp/1', //from: irs.nonprofitcorp 
 			'/DURC/nonprofitcorp/1/edit', //from: irs.nonprofitcorp 
 			'/DURC/inventorytransaction', //from: northwind_data.inventoryTransaction 
 			'/DURC/inventorytransaction/create', //from: northwind_data.inventoryTransaction 
 			'/DURC/inventorytransaction/1', //from: northwind_data.inventoryTransaction 
 			'/DURC/inventorytransaction/1/edit', //from: northwind_data.inventoryTransaction 
 			'/DURC/invoice', //from: northwind_data.invoice 
 			'/DURC/invoice/create', //from: northwind_data.invoice 
 			'/DURC/invoice/1', //from: northwind_data.invoice 
 			'/DURC/invoice/1/edit', //from: northwind_data.invoice 
 			'/DURC/order', //from: northwind_data.order 
 			'/DURC/order/create', //from: northwind_data.order 
 			'/DURC/order/1', //from: northwind_data.order 
 			'/DURC/order/1/edit', //from: northwind_data.order 
 			'/DURC/orderdetail', //from: northwind_data.orderDetail 
 			'/DURC/orderdetail/create', //from: northwind_data.orderDetail 
 			'/DURC/orderdetail/1', //from: northwind_data.orderDetail 
 			'/DURC/orderdetail/1/edit', //from: northwind_data.orderDetail 
 			'/DURC/purchaseorder', //from: northwind_data.purchaseOrder 
 			'/DURC/purchaseorder/create', //from: northwind_data.purchaseOrder 
 			'/DURC/purchaseorder/1', //from: northwind_data.purchaseOrder 
 			'/DURC/purchaseorder/1/edit', //from: northwind_data.purchaseOrder 
 			'/DURC/purchaseorderdetail', //from: northwind_data.purchaseOrderDetail 
 			'/DURC/purchaseorderdetail/create', //from: northwind_data.purchaseOrderDetail 
 			'/DURC/purchaseorderdetail/1', //from: northwind_data.purchaseOrderDetail 
 			'/DURC/purchaseorderdetail/1/edit', //from: northwind_data.purchaseOrderDetail 
 			'/DURC/appstring', //from: northwind_model.appstring 
 			'/DURC/appstring/create', //from: northwind_model.appstring 
 			'/DURC/appstring/1', //from: northwind_model.appstring 
 			'/DURC/appstring/1/edit', //from: northwind_model.appstring 
 			'/DURC/customer', //from: northwind_model.customer 
 			'/DURC/customer/create', //from: northwind_model.customer 
 			'/DURC/customer/1', //from: northwind_model.customer 
 			'/DURC/customer/1/edit', //from: northwind_model.customer 
 			'/DURC/employee', //from: northwind_model.employee 
 			'/DURC/employee/create', //from: northwind_model.employee 
 			'/DURC/employee/1', //from: northwind_model.employee 
 			'/DURC/employee/1/edit', //from: northwind_model.employee 
 			'/DURC/employeeprivilege', //from: northwind_model.employeePrivilege 
 			'/DURC/employeeprivilege/create', //from: northwind_model.employeePrivilege 
 			'/DURC/employeeprivilege/1', //from: northwind_model.employeePrivilege 
 			'/DURC/employeeprivilege/1/edit', //from: northwind_model.employeePrivilege 
 			'/DURC/inventorytransactiontype', //from: northwind_model.inventoryTransactionType 
 			'/DURC/inventorytransactiontype/create', //from: northwind_model.inventoryTransactionType 
 			'/DURC/inventorytransactiontype/1', //from: northwind_model.inventoryTransactionType 
 			'/DURC/inventorytransactiontype/1/edit', //from: northwind_model.inventoryTransactionType 
 			'/DURC/orderdetailstat', //from: northwind_model.orderDetailStat 
 			'/DURC/orderdetailstat/create', //from: northwind_model.orderDetailStat 
 			'/DURC/orderdetailstat/1', //from: northwind_model.orderDetailStat 
 			'/DURC/orderdetailstat/1/edit', //from: northwind_model.orderDetailStat 
 			'/DURC/orderstat', //from: northwind_model.orderStat 
 			'/DURC/orderstat/create', //from: northwind_model.orderStat 
 			'/DURC/orderstat/1', //from: northwind_model.orderStat 
 			'/DURC/orderstat/1/edit', //from: northwind_model.orderStat 
 			'/DURC/ordertaxstat', //from: northwind_model.orderTaxStat 
 			'/DURC/ordertaxstat/create', //from: northwind_model.orderTaxStat 
 			'/DURC/ordertaxstat/1', //from: northwind_model.orderTaxStat 
 			'/DURC/ordertaxstat/1/edit', //from: northwind_model.orderTaxStat 
 			'/DURC/privilege', //from: northwind_model.privilege 
 			'/DURC/privilege/create', //from: northwind_model.privilege 
 			'/DURC/privilege/1', //from: northwind_model.privilege 
 			'/DURC/privilege/1/edit', //from: northwind_model.privilege 
 			'/DURC/product', //from: northwind_model.product 
 			'/DURC/product/create', //from: northwind_model.product 
 			'/DURC/product/1', //from: northwind_model.product 
 			'/DURC/product/1/edit', //from: northwind_model.product 
 			'/DURC/purchaseorderstat', //from: northwind_model.purchaseOrderStat 
 			'/DURC/purchaseorderstat/create', //from: northwind_model.purchaseOrderStat 
 			'/DURC/purchaseorderstat/1', //from: northwind_model.purchaseOrderStat 
 			'/DURC/purchaseorderstat/1/edit', //from: northwind_model.purchaseOrderStat 
 			'/DURC/salesreport', //from: northwind_model.salesReport 
 			'/DURC/salesreport/create', //from: northwind_model.salesReport 
 			'/DURC/salesreport/1', //from: northwind_model.salesReport 
 			'/DURC/salesreport/1/edit', //from: northwind_model.salesReport 
 			'/DURC/shipper', //from: northwind_model.shipper 
 			'/DURC/shipper/create', //from: northwind_model.shipper 
 			'/DURC/shipper/1', //from: northwind_model.shipper 
 			'/DURC/shipper/1/edit', //from: northwind_model.shipper 
 			'/DURC/supplier', //from: northwind_model.supplier 
 			'/DURC/supplier/create', //from: northwind_model.supplier 
 			'/DURC/supplier/1', //from: northwind_model.supplier 
 			'/DURC/supplier/1/edit', //from: northwind_model.supplier 


	]; //end route_list

	$html = '<html><head><title>DURC Test Page</title><body><h1>DURC Test Page</h1><h3>DO NOT USE IN PRODUCTION!!!</h3>';

	$html .= '<ul>';

	foreach($route_list as $this_relative_link){
		$html  .= "<li><a href='$this_relative_link'>$this_relative_link </a> </li> ";
	}

	$html .= '</ul></body></html>';
	return $html;
}); //end DURC test route closure

Route::get('/',function () {
	$test_data = ['content' => '<h1>This is test content</h1>'];
	return view('DURC.durc_html',$test_data);
});
