<?php
/*
	This test route is automatically added.
	IF you would like to quickly see and test all of the index routes that are generated by DURC
	to use: http://[baseUrl]/durctest
	
	To remove routes from production, remove the require for this file from the register() method
	of the DURCServiceProvider.

*/

//This closure lists all of the index routes that DURC knows about...
Route::get('durctest', function () {
    $route_list = [ 




 			'/DURC/appstring', //from: northwind_model.appstring 
 			'/DURC/appstring/create', //from: northwind_model.appstring 
 			'/DURC/appstring/1', //from: northwind_model.appstring 
 			'/DURC/appstring/1/edit', //from: northwind_model.appstring 
 			'/DURC/customer', //from: northwind_model.customer 
 			'/DURC/customer/create', //from: northwind_model.customer 
 			'/DURC/customer/1', //from: northwind_model.customer 
 			'/DURC/customer/1/edit', //from: northwind_model.customer 
 			'/DURC/employee', //from: northwind_model.employee 
 			'/DURC/employee/create', //from: northwind_model.employee 
 			'/DURC/employee/1', //from: northwind_model.employee 
 			'/DURC/employee/1/edit', //from: northwind_model.employee 
 			'/DURC/employeeprivilege', //from: northwind_model.employeePrivilege 
 			'/DURC/employeeprivilege/create', //from: northwind_model.employeePrivilege 
 			'/DURC/employeeprivilege/1', //from: northwind_model.employeePrivilege 
 			'/DURC/employeeprivilege/1/edit', //from: northwind_model.employeePrivilege 
 			'/DURC/inventorytransactiontype', //from: northwind_model.inventoryTransactionType 
 			'/DURC/inventorytransactiontype/create', //from: northwind_model.inventoryTransactionType 
 			'/DURC/inventorytransactiontype/1', //from: northwind_model.inventoryTransactionType 
 			'/DURC/inventorytransactiontype/1/edit', //from: northwind_model.inventoryTransactionType 
 			'/DURC/orderdetailstat', //from: northwind_model.orderDetailStat 
 			'/DURC/orderdetailstat/create', //from: northwind_model.orderDetailStat 
 			'/DURC/orderdetailstat/1', //from: northwind_model.orderDetailStat 
 			'/DURC/orderdetailstat/1/edit', //from: northwind_model.orderDetailStat 
 			'/DURC/orderstat', //from: northwind_model.orderStat 
 			'/DURC/orderstat/create', //from: northwind_model.orderStat 
 			'/DURC/orderstat/1', //from: northwind_model.orderStat 
 			'/DURC/orderstat/1/edit', //from: northwind_model.orderStat 
 			'/DURC/ordertaxstat', //from: northwind_model.orderTaxStat 
 			'/DURC/ordertaxstat/create', //from: northwind_model.orderTaxStat 
 			'/DURC/ordertaxstat/1', //from: northwind_model.orderTaxStat 
 			'/DURC/ordertaxstat/1/edit', //from: northwind_model.orderTaxStat 
 			'/DURC/privilege', //from: northwind_model.privilege 
 			'/DURC/privilege/create', //from: northwind_model.privilege 
 			'/DURC/privilege/1', //from: northwind_model.privilege 
 			'/DURC/privilege/1/edit', //from: northwind_model.privilege 
 			'/DURC/product', //from: northwind_model.product 
 			'/DURC/product/create', //from: northwind_model.product 
 			'/DURC/product/1', //from: northwind_model.product 
 			'/DURC/product/1/edit', //from: northwind_model.product 
 			'/DURC/purchaseorderstat', //from: northwind_model.purchaseOrderStat 
 			'/DURC/purchaseorderstat/create', //from: northwind_model.purchaseOrderStat 
 			'/DURC/purchaseorderstat/1', //from: northwind_model.purchaseOrderStat 
 			'/DURC/purchaseorderstat/1/edit', //from: northwind_model.purchaseOrderStat 
 			'/DURC/salesreport', //from: northwind_model.salesReport 
 			'/DURC/salesreport/create', //from: northwind_model.salesReport 
 			'/DURC/salesreport/1', //from: northwind_model.salesReport 
 			'/DURC/salesreport/1/edit', //from: northwind_model.salesReport 
 			'/DURC/shipper', //from: northwind_model.shipper 
 			'/DURC/shipper/create', //from: northwind_model.shipper 
 			'/DURC/shipper/1', //from: northwind_model.shipper 
 			'/DURC/shipper/1/edit', //from: northwind_model.shipper 
 			'/DURC/supplier', //from: northwind_model.supplier 
 			'/DURC/supplier/create', //from: northwind_model.supplier 
 			'/DURC/supplier/1', //from: northwind_model.supplier 
 			'/DURC/supplier/1/edit', //from: northwind_model.supplier 


	]; //end route_list

	$html = '<html><head><title>DURC Test Page</title><body><h1>DURC Test Page</h1><h3>DO NOT USE IN PRODUCTION!!!</h3>';

	$html .= '<ul>';

	foreach($route_list as $this_relative_link){
		$html  .= "<li><a href='$this_relative_link'>$this_relative_link </a> </li> ";
	}

	$html .= '</ul></body></html>';
	return $html;
}); //end DURC test route closure

Route::get('/',function () {
	$test_data = ['content' => '<h1>This is test content</h1>'];
	return view('DURC.durc_html',$test_data);
});
